### ISSUE TITLE
gce_auth() error

### ISSUE THREAD

**Issue by Zack-M** [MarkEdmondson1234/googleAuthR#97]
Hi,

I am trying googleComputeEngineR for the first time, and my authorization was unsuccessful.
I ran the following code:
`library(googleComputeEngineR)

Sys.setenv(GCE_AUTH_FILE="/Volumes/E/GCP/rprojects-2017/NewKey.json",
           GCE_DEFAULT_PROJECT_ID = "rprojects-2017",
           GCE_DEFAULT_ZONE = "asia-southeast1-a")

gce_auth()`
 
The error message is as under:

**Error in googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  : 
  Cannot authenticate - options(googleAuthR.scopes.selected) needs to be set to includehttps://www.googleapis.com/auth/cloud-platform or https://www.googleapis.com/auth/compute
In addition: Warning message:
In googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  :
  travis_environment_var argument is now unsupported and does nothing**

Was unable to fix it, and any help would be great.

Best,
Zack

**Comment by MarkEdmondson1234** [comment]
For now set this before authentication:

```r
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")
```

...but I will look at if this is a bug.  May I see the results of your `sessionInfo()` ?

**Comment by Zack-M** [comment]
Hi Mark,

Thanks for the prompt revert.

It worked, and R-studio did get authorized but I am getting another strange error message for 
my project name (which is "rprojects-2017".)

When I run :
`gce_global_project("rprojects-2017)`

it throws this error:
**Error: Must be lowercase and/or hypens**

I mean, the project name is already in lowercase and contains only 1 hyphen. 
Any clue as to how may I fix this ?

Best,
Zack

**Comment by Zack-M** [comment]
And, my `sessionInfo()` is as under:

_R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.6_

**locale:**
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

**attached base packages:**
[1] splines   parallel  stats     graphics  grDevices utils     datasets  methods   base     

**other attached packages:**
 [1] gbm_2.1.3                  survival_2.41-3            randomForest_4.6-12        e1071_1.6-8                ipred_0.9-6               
 [6] klaR_0.6-12                MASS_7.3-47                kableExtra_0.5.2           knitr_1.16                 kernlab_0.9-25            
[11] nnet_7.3-12                caret_6.0-77               ggplot2_2.2.1              lattice_0.20-35            dplyr_0.5.0               
[16] plyr_1.8.4                 doMC_1.3.4                 iterators_1.0.8            foreach_1.4.3              googleAuthR_0.6.0         
[21] googleComputeEngineR_0.2.0

**loaded via a namespace:**
 [1] httr_1.3.1         ddalpha_1.3.1      sfsmisc_1.1-1      jsonlite_1.5       prodlim_1.6.1      assertthat_0.2.0   highr_0.6         
 [8] stats4_3.3.2       DRR_0.0.2          yaml_2.1.14        robustbase_0.92-7  globals_0.10.3     backports_1.1.0    digest_0.6.12     
[15] rvest_0.3.2        colorspace_1.3-2   recipes_0.1.0      htmltools_0.3.6    Matrix_1.2-10      timeDate_3012.100  CVST_0.2-1        
[22] listenv_0.6.0      purrr_0.2.2.2      scales_0.4.1       gower_0.1.2        lava_1.5.1         openssl_0.9.6      tibble_1.3.3      
[29] combinat_0.0-8     withr_2.0.0        lazyeval_0.2.0     magrittr_1.5       memoise_1.1.0      evaluate_0.10      future_1.6.2      
[36] nlme_3.1-131       xml2_1.1.1         dimRed_0.1.0       class_7.3-14       rsconnect_0.8      tools_3.3.2        hms_0.3           
[43] stringr_1.2.0      munsell_0.4.3      compiler_3.3.2     RcppRoll_0.2.2     rlang_0.1.1        grid_3.3.2         rmarkdown_1.6     
[50] gtable_0.2.0       ModelMetrics_1.1.0 codetools_0.2-15   curl_2.6           DBI_0.6-1          reshape2_1.4.2     R6_2.2.1          
[57] lubridate_1.6.0    rprojroot_1.2      readr_1.1.1        stringi_1.1.5      Rcpp_0.12.13       rpart_4.1-11       DEoptimR_1.0-8

**Comment by MarkEdmondson1234** [comment]
Ahh, this is this issue https://github.com/cloudyr/googleComputeEngineR/issues/72 which is fixed on GitHub version of `googleComputeEngineR`

If you install the GitHub version, it should be sorted.  

```r
source("https://install-github.me/cloudyr/googleComputeEngineR")
```

Otherwise, rename your project to not include numbers (sorry)

**Comment by Zack-M** [comment]
Hi Mark,

For some reason installing GitHub version of the package did not solve the problem but removing hyphens and numbers from the project name worked. 

Now, I've managed to create a VM but when I visit the IP provided, it keeps saying "**unable to connect to service**." 
I've tried starting from scratch on a completely new instance, with a new r-studio session, new  GCP project. Waited about 15-20 mins while the vm$status showed "RUNNING." 
Even tried different browsers without much luck. Still shows "unable to connect to service."

Any clue as to how may I fix this?

Many Thanks,
Zack

**Comment by MarkEdmondson1234** [comment]
Could I see the code you used?

**Comment by Zack-M** [comment]
Sure, here you go:
`options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")`
`library(googleComputeEngineR)`
`Sys.setenv(GCE_AUTH_FILE="/Volumes/E/GCP/rprojectsgcp/newkey.json",
           GCE_DEFAULT_PROJECT_ID = "rprojectsgcp",
           GCE_DEFAULT_ZONE = "asia-southeast1-a")
`
`gce_auth()`

`# Set default global project
project <- "rprojectsgcp"
gce_global_project(project)
gce_global_zone("asia-southeast1-a")`

`default_project <- gce_get_project("rprojectsgcp")`
`default_project$name`

# Defining vm 
`vm <- gce_vm(template = "rstudio",
             name = "rstudio-demo",
             username = "rstudio",
             password = "rforpresident",
             predefined_type="n1-highmem-2")
`
`vm$status`
## RUNNING

**Comment by Zack-M** [comment]
Hi Mark,

Any update?
I am still getting the same error - "unable to connect to service."

Best,
Zack

**Comment by MarkEdmondson1234** [comment]
Sorry I can't reproduce it so hard to pin down.

I would first check that the port is open - it should be - but in the Google Cloud VM dashboard see if ports 80/443 are open on the default network.

Then I would log into the VM itself, either via the console SSH command or via `gce_ssh_browser()` and check to see if the docker container is running via `docker ps` (or maybe `sudo docker ps`

If it is not running, then thats the issue, and you can then look at the Docker logs to see why it failed to launch.

If it is running, then its most likely a port issue again.  You can double check by logging in to the docker container itself `docker exec -it rstudio bash` 

Let me know how the above look. Also see website for some workflows https://cloudyr.github.io/googleComputeEngineR/articles/creating-vms.html

**Comment by wtzhou74** [comment]
Hi Mark,

I also got the same error "Rstudio Initialization Error - Unable to connect to service".
And `gce_list_firewallList()` shows that
< allowed direction
1                          tcp, 80   INGRESS
2                         tcp, 443   INGRESS
>
So I think, 80/443 are open on the default network. 
In addition, <docker ps> get the expected result that container is running. 
Do you have any thoughts about what is the root cause for this error? Are there any special requirements for the project? Like need to create folders with mkdir, etc.

Thanks,

**Comment by MarkEdmondson1234** [comment]
Hi @wtzhou74 may I see the code you used?  Did you authenticate with `gce_auth()` - it may be that instead you should auto-authenticate with the environment arguments e.g. as detailed here:
https://cloudyr.github.io/googleComputeEngineR/articles/installation-and-authentication.html#auto-authentication-via--renviron

If that doesn't work please issue your `sessionInfo()` so I can check it. 

If it does work then its an issue with `gce_auth()` that I should perhaps remove and say only use the environment arguments to authenticate.

**Comment by MarkEdmondson1234** [comment]
Ping @Zack-M as well - could you try to see if it works if you authenticate by not using `gce_auth()` but via downloading the json file and using environment arguments.

**Comment by wtzhou74** [comment]
@MarkEdmondson1234 Thanks, Below are the codes used:
```
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")
library(googleComputeEngineR)
# setup -----------------------------------
project <- "bmiteamproject"
zone <- "europe-west1-b"
account_key <- "gcs-key.json"
Sys.setenv(GCE_AUTH_FILE = account_key,
           GCE_DEFAULT_PROJECT_ID = project,
           GCE_DEFAULT_ZONE = zone)

gce_auth()

# set default global project
gce_global_project(project)
gce_global_zone(zone)

default_project <- gce_get_project("bmiteamproject")
default_project$name

VM <- gce_vm(template = "rstudio",
             name = "rstudio-demo",
             username = "rstudio",
             password = "rstudio",
             predefined_type = "n1-highmem-2")

gce_get_project()

my_rstudio <- gce_vm("rstudio-demo")
```

While as for another authentication, I created a file `.Renviron `and placed it in the my RProject home directory (Is it the right place?), no message showed in console as expected, for example, "Successfully authenticated via...."  when I run `library(googleComputeEngineR)`, so next, I get error when I run `gce_global_project()` because no project/zone was set. But, I think, this must be that I place the `.Renviron ` in the wrong place. So, could you tell me how to find the right home directory? I did not find the HOME button in RStudio’s file explorer.

**Comment by wtzhou74** [comment]
My` .Renviron` file looks like this:
```
GCE_AUTH_FILE="gcs-key.json"
GCE_DEFAULT_PROJECT_ID="bmiteamproject"
GCE_DEFAULT_ZONE="europe-west1-a"
```

And the structure of my project is 
```
bmiproject
      -- bmiproject.Rproj
      -- gcs-key.json
      -- rproject.R
      -- .Renviron
```

**Comment by wtzhou74** [comment]
Below are results of auto-authentication via` .Renviron`
```
> library(googleComputeEngineR)
> gce_get_project()
Error in gce_get_global_project() : 
  Project is NULL and couldn't find global project name.
         Set it via gce_global_project
```
Before I run  `library(googleComputeEngineR)`, `install.packages("googleComputeEngineR", dependencies = TRUE)` is required, right?

**Comment by wtzhou74** [comment]
These are the `sessionInfo()`
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleComputeEngineR_0.2.0

loaded via a namespace (and not attached):
 [1] googleAuthR_0.6.0 httr_1.3.1        R6_2.2.2          assertthat_0.2.0  parallel_3.3.2    tools_3.3.2      
 [7] listenv_0.6.0     memoise_1.1.0     codetools_0.2-15  jsonlite_1.5      digest_0.6.12     globals_0.10.3   
[13] future_1.6.2 
```

**Comment by MarkEdmondson1234** [comment]
In the RStudio file explorer, its the home link at the top.  

<img width="361" alt="screen shot 2017-11-03 at 20 45 26" src="https://user-images.githubusercontent.com/3155884/32392977-05602b24-c0d8-11e7-9c35-cb41fbd9d001.png">



> Before I run library(googleComputeEngineR), install.packages("googleComputeEngineR", dependencies = TRUE) is required, right?

No, you only need to install one time, but run the `library(googleComputeEngineR)` at the start of each new R session.

So:

```
#.Renvion
GCE_AUTH_FILE= "~/location/auth/gcs-key.json"
GCE_DEFAULT_PROJECT_ID="bmiteamproject"
GCE_DEFAULT_ZONE="europe-west1-b"
```

Restart R session once your R.environ is set. Bear in mine the `GCE_AUTH_FILE` needs to be a fully qualified file path, that doesn't look like the case above.

Then in R:
```r
library(googleComputeEngineR)
```
...you should get a message it auto-auth.  If not check your `.Renviron` again. 

Do not use `gce_auth()`, and the project Id etc. should be set already so no need for that code you have above dealing with that.

You should be able to run:
```r
gce_get_project()
```
..and see your project.

Then run 

```r
VM <- gce_vm(template = "rstudio",
             name = "rstudio-demo",
             username = "rstudio",
             password = "rstudio",
             predefined_type = "n1-highmem-2")
```

**Comment by wtzhou74** [comment]
Auto-authentication via library(googleComputeEngineR) works. But, I still get the error `"RStudio Intinization Error  Unable to connect to service"`
![image](https://user-images.githubusercontent.com/21085617/32397540-72b5a496-c0a7-11e7-9a78-3fb7afb32d83.png)

 The sessionInfo() is 
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleComputeEngineR_0.2.0

loaded via a namespace (and not attached):
 [1] codetools_0.2-15  listenv_0.6.0     future_1.6.2      digest_0.6.12     crayon_1.3.4      assertthat_0.2.0 
 [7] R6_2.2.2          jsonlite_1.5      magrittr_1.5      httr_1.3.1        curl_3.0          rstudioapi_0.7   
[13] testthat_1.0.2    googleAuthR_0.6.0 tools_3.3.2       parallel_3.3.2    globals_0.10.3    memoise_1.1.0    
[19] openssl_0.9.7 
```
And the `docker ps` shows that the container is running
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS          
        NAMES
e015b88d5393        rocker/tidyverse    "/init"             10 minutes ago      Up 10 minutes       0.0.0.0:80->878
7/tcp   rstudio
```

**Comment by wtzhou74** [comment]
@MarkEdmondson1234  Done!!! The username assigned during creating VM should be identical with the username of` /home/` on GCE. For example, on GCE, I have directory `/home/abc`, then the username assigned to the rstudio when creating VM should be `abc`. Also reference to `http://tonylixu.blogspot.com/2013/08/rstudio-rstudio-initialization-error.html`
Thanks,

**Comment by MarkEdmondson1234** [comment]
Ah great, I was scratching my head at that one :) I'll look into why your username was not created - hmm perhaps because you used `"rstudio"` which is already made for the service.  Does it work if you try another username?

**Comment by wtzhou74** [comment]
yes,  just like you said, probably it is due to that "rstudio" has been already made for the service.  I tried with another username, it works.

**Comment by MarkEdmondson1234** [comment]
@Zack-M Reopen if still an issue, but I have removed `gce_auth()` and suggest you try with JSON auto-auth instead

**Comment by wanhuiyan** [comment]
Hi Mark,

My JSON auto-auth fail to work 3 out of 5 times and I didn't change anything (I think), sometimes it just refuses to work :/

When I load the package, it says:
**No environment argument found, looked in GCE_AUTH_FILE**
But I do have a .Renviron file sitting in the same working directory:
`GCE_AUTH_FILE = "C:/Users/Huiyan/Documents/GCE/My First Project-060c08769789.json"
GCE_DEFAULT_PROJECT_ID = "graphic-adapter-161516"
GCE_DEFAULT_ZONE = "europe-west1-b"`

It was working fine this morning and suddenly it doesn't... Do you have any idea what is causing this? It might be some really stupid mistake but I can't figure out why. I am desperate... 

PS, I did also try this but it's not working neither:
`> Sys.setenv("GCE_AUTH_FILE" = "C:/Users/whyla/Documents/GCE/My First Project-060c08769789.json")
> gce_global_project("graphic-adapter-161516")
Error: Must be lowercase and/or hypens`

Here is my sessionInfo():
`> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleComputeEngineR_0.2.0.9000

loaded via a namespace (and not attached):
 [1] codetools_0.2-15       listenv_0.6.0          future_1.6.2           digest_0.6.12          withr_2.1.0            assertthat_0.2.0      
 [7] R6_2.2.2               jsonlite_1.5           httr_1.3.1             googleAuthR_0.6.2.9000 devtools_1.13.4        tools_3.4.3           
[13] yaml_2.1.15            parallel_3.4.3         compiler_3.4.3         globals_0.10.3         memoise_1.1.0        `

Thank you so much (for this, and for all the amazing packages you built! Big fan!)
Huiyan

**Comment by MarkEdmondson1234** [comment]
> When I load the package, it says:
> No environment argument found, looked in GCE_AUTH_FILE
> But I do have a .Renviron file sitting in the same working directory

That does suggest it is not finding the environment file - I would Google around for how to use `.Renviron` files for Windows, I guess its should go in `C://Users/whyla` but not 100% about that.  I've no idea why it should stop working, I guess perhaps R updated and is looking in a new location?  

All the help is in `?Startup` that goes into great detail on how these startup files all work together and how to set them. 

> gce_global_project("graphic-adapter-161516")
> Error: Must be lowercase and/or hypens`

That is unfortunately a bug that is fixed in the GitHub version, or rename your project-id to be without numbers.

**Comment by wanhuiyan** [comment]
Sorry I didn't expect you would reply so quickly!

I gave up on the JSON auto-auth method for now and managed to get the manual authentication to work by removing the numbers in my project-id. Thanks for your help! I was looking at the error message of "Must be lowercase and/or hyphens" and thinking, yes there is no uppercase nor underscore in my project-id... Stupid haha...

Thank you Mark!

**Comment by sdelear** [comment]
This is failing to setup using this code:
library(googleComputeEngineR)
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")
project <- "My_First_Project"
zone <- "us-central1-c"
account_key <- "My First Project-0eb899243c71.json"

Sys.setenv(GCE_AUTH_FILE = account_key,
           GCE_DEFAULT_PROJECT_ID = project,
           GCE_DEFAULT_ZONE = zone)
gce_auth()

and is giving the following error message:

Warning message:
In googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  :
  travis_environment_var argument is now unsupported and does nothing

I am using the project name as listed by google, thought vm itself is named rserver.  If JSON authentication is not going to work can you provide alternative code?

**Comment by MarkEdmondson1234** [comment]
The warning is just a warning, but it looks like you are using a project name rather than project-id in your settings.

**Comment by rmaranhao** [comment]
First, congrats! This seems to be awsome!

On Windows, you have to edit a file called
Renviron.site
and in my case located at
C:\Program Files\R\R-3.4.3\etc

As a suggestion, please make it possible to set the variables in the script before calling library(). I mean, make the code below work...

```
GCE_AUTH_FILE="D:/Roberto/_Tese/Google_Engine/R-Project-e290e616cfc1.json"
GCE_DEFAULT_PROJECT_ID="r-project-193916"
GCE_DEFAULT_ZONE="southamerica-east-c"
library(googleComputeEngineR)
```

As is, I cannot publish a working script because I must teach people to launch a text editor with admin privileges to set 3 variables. I will also be necessary to reconfigure R after every update, since the location of REnviron.site includes R's version number.

**Comment by MarkEdmondson1234** [comment]
Hi Roberto and thanks :)

You can set the environment arguments in the script instead of the file using Sys.env(“GCE_AUTH_FILE”) and similar, will that solve your issue?

________________________________

**Comment by MarkEdmondson1234** [comment]
Also you don’t need to edit Renviron.site - that’s a global file. You can set an .Renviron file in the same working directory, or in your computers home folder. See ?Startup for details.

________________________________

**Comment by vikrant-sahu** [comment]
When I restart my session I found that my installed packages are no longer available. What changes do I need to do so  that the packages remain in the VM even after sign out.

**Comment by MarkEdmondson1234** [comment]
@vikrant-sahu that sounds like a googleComputeEngineR issue?  IT sounds as if you are restarting the default Docker container, which will not save your changes - you should customise the Docker you launch from - seee here for details https://cloudyr.github.io/googleComputeEngineR/articles/rstudio-team.html#saving-the-docker-container-to-google-container-registry - if that doesn't help, please raise an issue on https://github.com/cloudyr/googleComputeEngineR/issues

**Comment by rmaranhao** [comment]
Thanks a lot!



Um grande abraço,
Roberto.

-- 
Roberto Maranhão - Maranhão Consultoria
r.maranhao@gmail.com
(5531) 8482 4456

2018-02-01 16:43 GMT-02:00 Mark <notifications@github.com>:

**Comment by tneyazi** [comment]
Hi Mark

While trying to run the package, i am getting the following message. Do you know what could be the inssue? 
> my_rstudio <- gce_vm("rstudio-demo")
Request failed [404]. Retrying in 1 seconds...
Request failed [404]. Retrying in 2.4 seconds...
2018-09-15 13:02:53> Request Status Code: 404
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Failed to find project indtest

I am using the following code
VM <- gce_vm(template = "rstudio",
             name = "rstudio-demo",
             username = "tabind",
             password = "rstudio",
             predefined_type = "n1-highmem-2")

gce_get_project()

my_rstudio <- gce_vm("rstudio-demo")

**Comment by MarkEdmondson1234** [comment]
Is your project-id “indtest”? Sounds too short, you should use the id not the project name perhaps that helps?

**Comment by tneyazi** [comment]
No, my project id is quite long. I am not sure why i am getting "indtest", which i used in my previous session, but had terminated the session. Any clue how to get rid of it?

**Comment by MarkEdmondson1234** [comment]
You can pass the project id explicitly into the function with the project argument, I guess you have the wrong project set in your environment arguments or via gce_global_project()

**Comment by hughandersen** [comment]
Hi Mark 
Thanks for the package, but I'm struggling to get a vm with Rstudio set up. Here is the file and console errors. I'm not sure why there is an error finding the project.

**Code**
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")
library(googleComputeEngineR)

#setup ----
project <- "hughsprojects-172704"  #the project ID NOT the project name, project name is hughs-projects
zone <- "australia-southeast1"
account_key <- "gcs_key.json"

Sys.setenv(GCE_AUTH_FILE=account_key,
           GCE_DEFAULT_PROJECT_ID=project,
           GCE_DEFAULT_ZONE=zone
           )

gce_auth()

#set default project
gce_global_project(project)
gce_global_zone(zone)

#r environment
vm <- gce_vm(template = "rstudio",
             name = "rstudio-cloud",
             username = "hugh",
             password = "rstudio-6311",
             predefined_type = "n1-highmem-2")

**Console output**
>options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")
> library(googleComputeEngineR)
> 
> #setup ----
> project <- "hughsprojects-172704"  #the project ID NOT the project name, project name is hughs-projects
> zone <- "australia-southeast1"
> account_key <- "gcs_key.json"
> 
> Sys.setenv(GCE_AUTH_FILE=account_key,
+            GCE_DEFAULT_PROJECT_ID=project,
+            GCE_DEFAULT_ZONE=zone
+            )
> 
> gce_auth()
Warning message:
In googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  :
  travis_environment_var argument is now unsupported and does nothing
> 
> #set default project
> gce_global_project(project)
Error: Must be lowercase and/or hypens
> gce_global_zone(zone)
Set default zone name to 'australia-southeast1'
> 
> #r environment
> vm <- gce_vm(template = "rstudio",
+              name = "rstudio-cloud",
+              username = "hugh",
+              password = "rstudio-6311",
+              predefined_type = "n1-highmem-2")
Request failed [404]. Retrying in 1.6 seconds...
Request failed [404]. Retrying in 1 seconds...
2018-10-12 17:00:26> Request Status Code: 404
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Failed to find project hughs-projects

**Comment by MarkEdmondson1234** [comment]
Hi @hughandersen , This is this bug issue https://github.com/cloudyr/googleComputeEngineR/issues/72 which is fixed if you install the GitHub version of `googleComputeEngineR`

**Comment by hughandersen** [comment]
Thanks Mark I'll try your solution

**Comment by IbandLu** [comment]
@MarkEdmondson1234 Any help why this code doesn't work would be appreciated. I've tried the solutions that have been suggested above

# source("https://install-github.me/cloudyr/googleComputeEngineR")
Sys.setenv(GCE_AUTH_FILE = account_key,
           GCE_DEFAULT_PROJECT_ID = project,
           GCE_DEFAULT_ZONE= zone)
library(googleComputeEngineR)

# Setup -------------------------------------------------------------------
setwd("D:/Users/Ilona Box/Documents/Research/BurrupRockArt/LandsatData/WorkingLandSatData")
options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/analytics",
                                        "https://www.googleapis.com/auth/analytics.readonly", 
                                        "https://www.googleapis.com/auth/webmasters",
                                        "https://www.googleapis.com/auth/cloud-platform"))

project <- "invertible-oath-223807" #My First Project
zone <- "australia-southeast1-b"
account_key <- "Key.json"


# # Sys.setenv(GCE_AUTH_FILE = account_key,
#            GCE_DEFAULT_PROJECT_ID = project,
#            GCE_DEFAULT_ZONE= zone)

gce_auth()

# Set our default global project
gce_global_project(project)
gce_global_zone(zone)

default_project <- gce_get_project("invertible-oath-223807")
default_project$name

The console:

> gce_auth()
Error in googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  : 
  GCE_AUTH_FILE specified in environment variables but file not found - 
           looked for Key.json and called from D:/Users/Ilona Box/Documents/Research/BurrupRockArt/LandsatData/WorkingLandSatData
In addition: Warning message:
In googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  :
  travis_environment_var argument is now unsupported and does nothing
> 
> # Set our default global project
> gce_global_project(project)
Error: Must be lowercase and/or hypens
> gce_global_zone(zone)
Set default zone name to 'australia-southeast1-b'
> 
> default_project <- gce_get_project("invertible-oath-223807")
2018-11-30 19:23:48> No authorization yet in this session!
2018-11-30 19:23:48> No  .httr-oauth  file exists in current working directory.  Do library authentication steps to provide credentials.
Error: Invalid token
> default_project$name
Error: object 'default_project' not found

This shouldn't be so hard should it?

**Comment by IbandLu** [comment]
@MarkEdmondson1234 All the bold parts above are comments.
In aniticipation: Thanks for your attention to this matter.

Session info
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleComputeEngineR_0.2.0 RevoUtilsMath_10.0.1       RevoUtils_10.0.7           RevoMods_11.0.0           
[5] MicrosoftML_9.3.0          mrsdeploy_1.1.3            RevoScaleR_9.3.0           lattice_0.20-35           
[9] rpart_4.1-11              

loaded via a namespace (and not attached):
 [1] codetools_0.2-15       listenv_0.6.0          future_1.6.2           CompatibilityAPI_1.1.0 digest_0.6.13         
 [6] assertthat_0.2.0       foreach_1.4.5          grid_3.4.3             R6_2.2.2               jsonlite_1.5          
[11] httr_1.3.1             curl_3.1               googleAuthR_0.7.0.9000 iterators_1.0.9        tools_3.4.3           
[16] parallel_3.4.3         compiler_3.4.3         memoise_1.1.0          globals_0.10.3         mrupdate_1.0.1        
> 

BTW Newbie to R and GCP

**Comment by MarkEdmondson1234** [comment]
Hi @IbandLu it looks like this is due this issue https://github.com/cloudyr/googleComputeEngineR/issues/72 so updating the package from github should solve it.

If you get any other issues please open an issue on that repo as its really difficult to keep track of in this issue.

I'm locking this issue as its on top of Google or something so new issues keep being put on it - please do create a new issue if you need help and do it on the https://github.com/cloudyr/googleComputeEngineR/issues issues if its related to that.

**Comment by MarkEdmondson1234** [comment]
I'm locking this issue as its on top of Google or something so new issues keep being put on it - please do create a new issue if you need help and do it on the https://github.com/cloudyr/googleComputeEngineR/issues issues if its related to that.
